In [4]:
import pandas as pd
import numpy as np
import math

In [5]:
df=pd.read_csv('/home/sfs1721/Desktop/ML 03.05.19/MLworkshop/Mall_Customers.csv')
df

     CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male   19                  15                      39
1             2    Male   21                  15                      81
2             3  Female   20                  16                       6
3             4  Female   23                  16                      77
4             5  Female   31                  17                      40
5             6  Female   22                  17                      76
6             7  Female   35                  18                       6
7             8  Female   23                  18                      94
8             9    Male   64                  19                       3
9            10  Female   30                  19                      72
10           11    Male   67                  19                      14
11           12  Female   35                  19                      99
12           13  Female   58                  20                      15
13           14  Female   24                  20                      77
14           15    Male   37                  20                      13
15           16    Male   22                  20                      79
16           17  Female   35                  21                      35
17           18    Male   20                  21                      66
18           19    Male   52                  23                      29
19           20  Female   35                  23                      98
20           21    Male   35                  24                      35
21           22    Male   25                  24                      73
22           23  Female   46                  25                       5
23           24    Male   31                  25                      73
24           25  Female   54                  28                      14
25           26    Male   29                  28                      82
26           27  Female   45                  28                      32
27           28    Male   35                  28                      61
28           29  Female   40                  29                      31
29           30  Female   23                  29                      87
..          ...     ...  ...                 ...                     ...
170         171    Male   40                  87                      13
171         172    Male   28                  87                      75
172         173    Male   36                  87                      10
173         174    Male   36                  87                      92
174         175  Female   52                  88                      13
175         176  Female   30                  88                      86
176         177    Male   58                  88                      15
177         178    Male   27                  88                      69
178         179    Male   59                  93                      14
179         180    Male   35                  93                      90
180         181  Female   37                  97                      32
181         182  Female   32                  97                      86
182         183    Male   46                  98                      15
183         184  Female   29                  98                      88
184         185  Female   41                  99                      39
185         186    Male   30                  99                      97
186         187  Female   54                 101                      24
187         188    Male   28                 101                      68
188         189  Female   41                 103                      17
189         190  Female   36                 103                      85
190         191  Female   34                 103                      23
191         192  Female   32                 103                      69
192         193    Male   33                 113                       8
193         194  Female   38                 113                      91
194         195  Female   47                 120                      16
195         196  Female   35                 120                      79
196         197  Female   45                 126                      28
197         198    Male   32                 126                      74
198         199    Male   32                 137                      18
199         200    Male   30                 137                      83

[200 rows x 5 columns]

df.isnull().sum()

In [6]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

print(df.shape[1])

In [7]:
from sklearn.model_selection import train_test_split
labels=df['Spending Score (1-100)']
df_train=df.drop(['Spending Score (1-100)'],axis=1)
x_train,x_test,y_train,y_test=train_test_split(df_train,labels,test_size=0.2)

In [12]:
x_train()

TypeError: 'DataFrame' object is not callable

In [39]:
x_train

     CustomerID  Gender  Age  Annual Income (k$)
171         172    Male   28                  87
26           27  Female   45                  28
77           78    Male   40                  54
31           32  Female   21                  30
35           36  Female   21                  33
145         146    Male   28                  77
37           38  Female   30                  34
53           54    Male   59                  43
69           70  Female   32                  48
14           15    Male   37                  20
110         111    Male   65                  63
2             3  Female   20                  16
128         129    Male   59                  71
91           92    Male   18                  59
34           35  Female   49                  33
49           50  Female   31                  40
94           95  Female   32                  60
63           64  Female   54                  47
141         142    Male   32                  75
115         116  Female   19                  65
162         163    Male   19                  81
41           42    Male   24                  38
102         103    Male   67                  62
134         135    Male   20                  73
176         177    Male   58                  88
107         108    Male   54                  63
114         115  Female   18                  65
89           90  Female   50                  58
142         143  Female   28                  76
121         122  Female   38                  67
..          ...     ...  ...                 ...
156         157    Male   37                  78
25           26    Male   29                  28
149         150    Male   34                  78
78           79  Female   23                  54
165         166  Female   36                  85
167         168  Female   33                  86
163         164  Female   31                  81
57           58    Male   69                  44
18           19    Male   52                  23
130         131    Male   47                  71
133         134  Female   31                  72
97           98  Female   27                  60
51           52    Male   33                  42
170         171    Male   40                  87
5             6  Female   22                  17
75           76    Male   26                  54
96           97  Female   47                  60
8             9    Male   64                  19
59           60    Male   53                  46
70           71    Male   70                  49
132         133  Female   25                  72
1             2    Male   21                  15
146         147    Male   48                  77
29           30  Female   23                  29
131         132    Male   39                  71
60           61    Male   70                  46
144         145    Male   25                  77
191         192  Female   32                 103
92           93    Male   48                  60
88           89  Female   34                  58

[160 rows x 4 columns]

In [41]:
y_train

171    75
26     32
77     48
31     73
35     81
145    97
37     73
53     60
69     47
14     13
110    52
2       6
128    11
91     41
34     14
49     42
94     42
63     59
141    93
115    50
162     5
41     92
102    59
134     5
176    15
107    46
114    48
89     46
142    40
121    40
       ..
156     1
25     82
149    90
78     52
165    75
167    95
163    93
57     46
18     29
130     9
133    71
97     50
51     60
170    13
5      76
75     54
96     47
8       3
59     46
70     55
132    34
1      81
146    36
29     87
131    75
60     56
144    12
191    69
92     49
88     60
Name: Spending Score (1-100), Length: 160, dtype: int64

In [8]:
df.isnull().sum()

CustomerID                0
Gender                    0
Age                       0
Annual Income (k$)        0
Spending Score (1-100)    0
dtype: int64

In [45]:
x_test

     CustomerID  Gender  Age  Annual Income (k$)
83           84  Female   46                  54
6             7  Female   35                  18
85           86    Male   48                  54
45           46  Female   24                  39
86           87  Female   55                  57
9            10  Female   30                  19
150         151    Male   43                  78
192         193    Male   33                 113
126         127    Male   43                  71
38           39  Female   36                  37
193         194  Female   38                 113
137         138    Male   32                  73
68           69    Male   19                  48
138         139    Male   19                  74
50           51  Female   49                  42
90           91  Female   68                  59
3             4  Female   23                  16
197         198    Male   32                 126
111         112  Female   19                  63
95           96    Male   24                  60
127         128    Male   40                  71
30           31    Male   60                  30
136         137  Female   44                  73
182         183    Male   46                  98
151         152    Male   39                  78
64           65    Male   63                  48
48           49  Female   29                  40
72           73  Female   60                  50
39           40  Female   20                  37
148         149  Female   34                  78
166         167    Male   42                  86
184         185  Female   41                  99
43           44  Female   31                  39
101         102  Female   49                  62
199         200    Male   30                 137
183         184  Female   29                  98
120         121    Male   27                  67
159         160  Female   30                  78
154         155  Female   47                  78
4             5  Female   31                  17

In [9]:
import pandas as pd

In [14]:
training=pd.get_dummies(, columns=["Gender"])
#training.drop('Sex_female', axis=1, )

In [16]:
training

,CustomerID,Age,Annual Income (k$),Spending Score (1-100),Gender_Female,Gender_Male
0,1,19,15,39,0,1
1,2,21,15,81,0,1
2,3,20,16,6,1,0
3,4,23,16,77,1,0
4,5,31,17,40,1,0
5,6,22,17,76,1,0
6,7,35,18,6,1,0
7,8,23,18,94,1,0
8,9,64,19,3,0,1
9,10,30,19,72,1,0
10,11,67,19,14,0,1
11,12,35,19,99,1,0
12,13,58,20,15,1,0
13,14,24,20,77,1,0
14,15,37,20,13,0,1
15,16,22,20,79,0,1
16,17,35,21,35,1,0
17,18,20,21,66,0,1
18,19,52,23,29,0,1
19,20,35,23,98,1,0
20,21,35,24,35,0,1
21,22,25,24,73,0,1
22,23,46,25,5,1,0
23,24,31,25,73,0,1
24,25,54,28,14,1,0
25,26,29,28,82,0,1
26,27,45,28,32,1,0
27,28,35,28,61,0,1
28,29,40,29,31,1,0
29,30,23,29,87,1,0
...,...,...,...,...,...,...
170,171,40,87,13,0,1
171,172,28,87,75,0,1
172,173,36,87,10,0,1
173,174,36,87,92,0,1
174,175,52,88,13,1,0
175,176,30,88,86,1,0
176,177,58,88,15,0,1
177,178,27,88,69,0,1
178,179,59,93,14,0,1
179,180,35,93,90,0,1
180,181,37,97,32,1,0
181,182,32,97,86,1,0
182,183,46,98,15,0,1
183,184,29,98,88,1,0
184,185,41,99,39,1,0
185,186,30,99,97,0,1
186,187,54,101,24,1,0
187,188,28,101,68,0,1
188,189,41,103,17,1,0
189,190,36,103,85,1,0
190,191,34,103,23,1,0
191,192,32,103,69,1,0
192,193,33,113,8,0,1
193,194,38,113,91,1,0
194,195,47,120,16,1,0
195,196,35,120,79,1,0
196,197,45,126,28,1,0
197,198,32,126,74,0,1
198,199,32,137,18,0,1
199,200,30,137,83,0,1

KeyError: "['Gender'] not found in axis"

In [63]:
training.drop('M_F',axis=1,inplace=True)

In [55]:
training['M_F']=np.where(training['Age']=="Male", 1, 0)

In [19]:
training

,CustomerID,Age,Annual Income (k$),Spending Score (1-100),Gender_Female,Gender_Male
0,1,19,15,39,0,1
1,2,21,15,81,0,1
2,3,20,16,6,1,0
3,4,23,16,77,1,0
4,5,31,17,40,1,0
5,6,22,17,76,1,0
6,7,35,18,6,1,0
7,8,23,18,94,1,0
8,9,64,19,3,0,1
9,10,30,19,72,1,0
10,11,67,19,14,0,1
11,12,35,19,99,1,0
12,13,58,20,15,1,0
13,14,24,20,77,1,0
14,15,37,20,13,0,1
15,16,22,20,79,0,1
16,17,35,21,35,1,0
17,18,20,21,66,0,1
18,19,52,23,29,0,1
19,20,35,23,98,1,0
20,21,35,24,35,0,1
21,22,25,24,73,0,1
22,23,46,25,5,1,0
23,24,31,25,73,0,1
24,25,54,28,14,1,0
25,26,29,28,82,0,1
26,27,45,28,32,1,0
27,28,35,28,61,0,1
28,29,40,29,31,1,0
29,30,23,29,87,1,0
...,...,...,...,...,...,...
170,171,40,87,13,0,1
171,172,28,87,75,0,1
172,173,36,87,10,0,1
173,174,36,87,92,0,1
174,175,52,88,13,1,0
175,176,30,88,86,1,0
176,177,58,88,15,0,1
177,178,27,88,69,0,1
178,179,59,93,14,0,1
179,180,35,93,90,0,1
180,181,37,97,32,1,0
181,182,32,97,86,1,0
182,183,46,98,15,0,1
183,184,29,98,88,1,0
184,185,41,99,39,1,0
185,186,30,99,97,0,1
186,187,54,101,24,1,0
187,188,28,101,68,0,1
188,189,41,103,17,1,0
189,190,36,103,85,1,0
190,191,34,103,23,1,0
191,192,32,103,69,1,0
192,193,33,113,8,0,1
193,194,38,113,91,1,0
194,195,47,120,16,1,0
195,196,35,120,79,1,0
196,197,45,126,28,1,0
197,198,32,126,74,0,1
198,199,32,137,18,0,1
199,200,30,137,83,0,1

In [18]:
training

,CustomerID,Age,Annual Income (k$),Spending Score (1-100),Gender_Female,Gender_Male
0,1,19,15,39,0,1
1,2,21,15,81,0,1
2,3,20,16,6,1,0
3,4,23,16,77,1,0
4,5,31,17,40,1,0
5,6,22,17,76,1,0
6,7,35,18,6,1,0
7,8,23,18,94,1,0
8,9,64,19,3,0,1
9,10,30,19,72,1,0
10,11,67,19,14,0,1
11,12,35,19,99,1,0
12,13,58,20,15,1,0
13,14,24,20,77,1,0
14,15,37,20,13,0,1
15,16,22,20,79,0,1
16,17,35,21,35,1,0
17,18,20,21,66,0,1
18,19,52,23,29,0,1
19,20,35,23,98,1,0
20,21,35,24,35,0,1
21,22,25,24,73,0,1
22,23,46,25,5,1,0
23,24,31,25,73,0,1
24,25,54,28,14,1,0
25,26,29,28,82,0,1
26,27,45,28,32,1,0
27,28,35,28,61,0,1
28,29,40,29,31,1,0
29,30,23,29,87,1,0
...,...,...,...,...,...,...
170,171,40,87,13,0,1
171,172,28,87,75,0,1
172,173,36,87,10,0,1
173,174,36,87,92,0,1
174,175,52,88,13,1,0
175,176,30,88,86,1,0
176,177,58,88,15,0,1
177,178,27,88,69,0,1
178,179,59,93,14,0,1
179,180,35,93,90,0,1
180,181,37,97,32,1,0
181,182,32,97,86,1,0
182,183,46,98,15,0,1
183,184,29,98,88,1,0
184,185,41,99,39,1,0
185,186,30,99,97,0,1
186,187,54,101,24,1,0
187,188,28,101,68,0,1
188,189,41,103,17,1,0
189,190,36,103,85,1,0
190,191,34,103,23,1,0
191,192,32,103,69,1,0
192,193,33,113,8,0,1
193,194,38,113,91,1,0
194,195,47,120,16,1,0
195,196,35,120,79,1,0
196,197,45,126,28,1,0
197,198,32,126,74,0,1
198,199,32,137,18,0,1
199,200,30,137,83,0,1

In [20]:
from sklearn.model_selection import train_test_split
labels=training['Spending Score (1-100)']
train_data=training.drop(['Spending Score (1-100)'],axis=1)
x_train,x_test,y_train,y_test=train_test_split(train_data,labels,test_size=0.2)

In [23]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [24]:
model.fit(x_train,y_train)
prediction=model.predict(x_test)

/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/usr/local/lib/python3.5/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

In [ ]:
x_train